spring:
  application:
    name: business-oauth2
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.163.130:3306/market?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
      username: root
      password: admin123
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.163.133:8848
  redis:
    # 你 Redis 主机地址
    host: 192.168.163.135
    # 你 Redis 主机端口
    port: 6379
    # 集群配置，上生产后使用
    #   cluster:
    #     nodes: ${base.config.redis.hostname}:${base.config.redis.port}
    # 我们使用 Lettuce 客户端，比 Jedis 更高效
    lettuce:
      # 连接池配置
      pool:
        # 连接池中的最小空闲连接，默认 0
        min-idle: 0
        # 连接池中的最大空闲连接，默认 8
        max-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制），默认 -1ms
        max-wait: -1ms
        # 连接池最大连接数（使用负值表示没有限制），默认 8
        max-active: 8
      # Redis 高可用集群，由于 K8S 帮我们实现了高可用，这个可以忽略了
    #    sentinel:
    #      master: mymaster
    #      nodes: ${base.config.redis.hostname}:26379
server:
  port: 9001
dubbo:
  scan:
    base-packages: com.cosmax.shop.system.business.oauth2
  protocol:
    name: dubbo
    serialization: kryo
    port: -1

  registry:
    address: nacos://192.168.163.133
    port: 8848

feign:
  sentinel:
    enabled: true
