auth-server-url: http://localhost:9001 # 授权服务地址

spring:
  application:
    name: message-login-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.163.133:8848
    stream:
      rocketmq:
        binder:
          name-server: 192.168.163.135:9876
      bindings:
        login-log-topic:
          destination: login-log-topic
          content-type: application/json
          group: admin-login-log-group
          consumer.maxAttempts: 1
server:
  port: 10002
dubbo:
  scan:
    base-packages: com.cosmax.shop.sytem.message.login.consumer
  protocol:
    name: dubbo
    serialization: kryo
    port: -1

  registry:
    address: nacos://192.168.163.133:8848
    port: 80


